SET @sql := IF(
  EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='hizmetler' AND COLUMN_NAME='kdv_orani'),
  'SELECT 1',
  'ALTER TABLE hizmetler ADD COLUMN kdv_orani DECIMAL(5,2) NULL AFTER ucret'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql := IF(
  EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='paketler' AND COLUMN_NAME='kdv_orani'),
  'SELECT 1',
  'ALTER TABLE paketler ADD COLUMN kdv_orani DECIMAL(5,2) NULL AFTER net_paket_tutari'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
