SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS kurum_entegrasyonlari (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  kurum_id BIGINT UNSIGNED NOT NULL,
  provider VARCHAR(40) NOT NULL DEFAULT 'mysoft',
  base_url VARCHAR(255) NOT NULL,
  ortam VARCHAR(20) NOT NULL DEFAULT 'test',
  tenant_identifier_number VARCHAR(20) NOT NULL,
  client_id VARCHAR(255) NULL,
  client_secret_sifreli TEXT NULL,
  efatura_prefix VARCHAR(20) NULL,
  earsiv_prefix VARCHAR(20) NULL,
  numerator_set_code VARCHAR(100) NULL,
  gb_alias VARCHAR(255) NULL,
  varsayilan_efatura_profili VARCHAR(40) NOT NULL DEFAULT 'TEMELFATURA',
  aktif TINYINT(1) NOT NULL DEFAULT 0,
  otomatik_fatura TINYINT(1) NOT NULL DEFAULT 0,
  olusturulma_tarihi DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  guncellenme_tarihi DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_kurum_entegrasyon_provider (kurum_id, provider),
  KEY idx_kurum_entegrasyon_aktif (kurum_id, aktif),
  CONSTRAINT fk_kurum_entegrasyon_kurum FOREIGN KEY (kurum_id) REFERENCES kurumlar(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS fatura_profilleri (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  kurum_id BIGINT UNSIGNED NOT NULL,
  veli_id BIGINT UNSIGNED NOT NULL,
  profil_turu ENUM('bireysel','kurumsal') NOT NULL DEFAULT 'bireysel',
  ad VARCHAR(120) NULL,
  soyad VARCHAR(120) NULL,
  unvan VARCHAR(500) NULL,
  vkn_tckn VARCHAR(20) NOT NULL,
  vergi_dairesi VARCHAR(190) NULL,
  adres TEXT NOT NULL,
  il VARCHAR(100) NOT NULL,
  ilce VARCHAR(100) NOT NULL,
  ulke VARCHAR(100) NOT NULL DEFAULT 'TÜRKİYE',
  eposta VARCHAR(190) NULL,
  telefon VARCHAR(40) NULL,
  aktif TINYINT(1) NOT NULL DEFAULT 1,
  olusturulma_tarihi DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  guncellenme_tarihi DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_fatura_profili_veli (kurum_id, veli_id),
  KEY idx_fatura_profili_vkn (kurum_id, vkn_tckn),
  CONSTRAINT fk_fatura_profili_kurum FOREIGN KEY (kurum_id) REFERENCES kurumlar(id) ON DELETE CASCADE,
  CONSTRAINT fk_fatura_profili_veli FOREIGN KEY (veli_id) REFERENCES veliler(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS faturalar (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  kurum_id BIGINT UNSIGNED NOT NULL,
  entegrasyon_id BIGINT UNSIGNED NULL,
  odeme_id BIGINT UNSIGNED NULL,
  veli_id BIGINT UNSIGNED NULL,
  ogrenci_id BIGINT UNSIGNED NULL,
  kaynak ENUM('application','mysoft') NOT NULL DEFAULT 'application',
  belge_turu VARCHAR(30) NOT NULL,
  profil VARCHAR(40) NOT NULL,
  fatura_tipi VARCHAR(40) NOT NULL DEFAULT 'SATIS',
  ettn CHAR(36) NOT NULL,
  referans_anahtari VARCHAR(100) NULL,
  mysoft_invoice_id BIGINT NULL,
  fatura_no VARCHAR(50) NULL,
  fatura_tarihi DATE NOT NULL,
  fatura_saati TIME NULL,
  para_birimi VARCHAR(10) NOT NULL DEFAULT 'TRY',
  ara_toplam DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  kdv_toplami DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  genel_toplam DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  alici_adi VARCHAR(500) NOT NULL,
  alici_vkn_tckn VARCHAR(20) NOT NULL,
  yerel_durum VARCHAR(40) NOT NULL DEFAULT 'olusturuluyor',
  mysoft_durum VARCHAR(100) NULL,
  hata_kodu VARCHAR(100) NULL,
  hata_mesaji TEXT NULL,
  son_http_durumu SMALLINT NULL,
  son_cevap JSON NULL,
  gonderilme_tarihi DATETIME NULL,
  durum_sorgulama_tarihi DATETIME NULL,
  iptal_tarihi DATETIME NULL,
  olusturulma_tarihi DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  guncellenme_tarihi DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_fatura_odeme (kurum_id, odeme_id),
  UNIQUE KEY uq_fatura_ettn (kurum_id, ettn),
  KEY idx_fatura_liste (kurum_id, fatura_tarihi, id),
  KEY idx_fatura_durum (kurum_id, yerel_durum),
  CONSTRAINT fk_fatura_kurum FOREIGN KEY (kurum_id) REFERENCES kurumlar(id) ON DELETE CASCADE,
  CONSTRAINT fk_fatura_entegrasyon FOREIGN KEY (entegrasyon_id) REFERENCES kurum_entegrasyonlari(id) ON DELETE SET NULL,
  CONSTRAINT fk_fatura_odeme FOREIGN KEY (odeme_id) REFERENCES odemeler(id) ON DELETE RESTRICT,
  CONSTRAINT fk_fatura_veli FOREIGN KEY (veli_id) REFERENCES veliler(id) ON DELETE SET NULL,
  CONSTRAINT fk_fatura_ogrenci FOREIGN KEY (ogrenci_id) REFERENCES ogrenciler(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS fatura_kalemleri (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  kurum_id BIGINT UNSIGNED NOT NULL,
  fatura_id BIGINT UNSIGNED NOT NULL,
  aciklama VARCHAR(500) NOT NULL,
  miktar DECIMAL(14,4) NOT NULL DEFAULT 1.0000,
  birim_kodu VARCHAR(20) NOT NULL DEFAULT 'C62',
  birim_fiyat DECIMAL(14,4) NOT NULL,
  kdv_orani DECIMAL(7,4) NOT NULL DEFAULT 0.0000,
  kdv_tutari DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  satir_toplami DECIMAL(14,2) NOT NULL,
  olusturulma_tarihi DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_fatura_kalemleri_fatura (kurum_id, fatura_id),
  CONSTRAINT fk_fatura_kalemi_kurum FOREIGN KEY (kurum_id) REFERENCES kurumlar(id) ON DELETE CASCADE,
  CONSTRAINT fk_fatura_kalemi_fatura FOREIGN KEY (fatura_id) REFERENCES faturalar(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
