<?php

declare(strict_types=1);

use App\Controllers\GirisController;
use App\Controllers\BekleyenVeliController;
use App\Controllers\GrupController;
use App\Controllers\GunlukKayitController;
use App\Controllers\HaftalikTemaController;
use App\Controllers\KasaController;
use App\Controllers\KullaniciController;
use App\Controllers\KurumController;
use App\Controllers\FaturaController;
use App\Controllers\CariController;
use App\Controllers\OdemeController;
use App\Controllers\OgrenciController;
use App\Controllers\OnamFormuController;
use App\Controllers\PaketController;
use App\Controllers\RandevuController;
use App\Controllers\RandevuKatilimController;
use App\Controllers\PanelController;
use App\Controllers\PersonelController;
use App\Controllers\RaporController;
use App\Controllers\SmsController;
use App\Controllers\VeliController;
use App\Controllers\VeliPortalController;
use App\Controllers\VeliOnamController;
use App\Controllers\MfaController;
use App\Core\Router;

return function (Router $router): void {
    $router->get('/', [GirisController::class, 'form']);
    $router->get('/giris', [GirisController::class, 'form']);
    $router->post('/giris', [GirisController::class, 'giris']);
    $router->get('/mfa', [MfaController::class, 'form']);
    $router->post('/mfa', [MfaController::class, 'dogrula']);
    $router->post('/cikis', [GirisController::class, 'cikis']);
    $router->get('/veli-portal', [VeliPortalController::class, 'form']);
    $router->post('/veli-portal', [VeliPortalController::class, 'dogrula']);
    $router->get('/oyun-grubu-onam', [VeliOnamController::class, 'form']);
    $router->post('/oyun-grubu-onam', [VeliOnamController::class, 'kaydet']);
    $router->get('/randevu-katilim', [RandevuKatilimController::class, 'form']);
    $router->post('/randevu-katilim', [RandevuKatilimController::class, 'kaydet']);
    $router->get('/panel', [PanelController::class, 'genelBakis']);
    $router->get('/panel/guvenlik/mfa', [MfaController::class, 'ayarlar']);
    $router->post('/panel/guvenlik/mfa', [MfaController::class, 'etkinlestir']);
    $router->get('/panel/ogrenciler', [OgrenciController::class, 'sayfa'], 'ogrenci_listele');
    $router->get('/panel/ogrenciler/yeni', [OgrenciController::class, 'yeniKayit'], 'ogrenci_ekle');
    $router->get('/panel/ogrenciler/import-sablonu.xlsx', [OgrenciController::class, 'topluImportSablonu'], 'ogrenci_ekle');
    $router->post('/panel/ogrenciler/import', [OgrenciController::class, 'topluImport'], 'ogrenci_ekle');
    $router->get('/panel/ogrenciler/profil', [OgrenciController::class, 'profil'], 'ogrenci_listele');
    $router->get('/panel/ogrenciler/kara-liste', [OgrenciController::class, 'karaListeSayfa'], 'ogrenci_listele');
    $router->get('/panel/ogrenciler/tedbir-listesi', [OgrenciController::class, 'karaListeSayfa'], 'ogrenci_listele');
    $router->get('/panel/ogrenciler/devamlilik-raporu', [OgrenciController::class, 'devamlilikRaporuSayfa'], 'ogrenci_listele');
    $router->get('/panel/ogrenciler/adres-haritasi', [OgrenciController::class, 'adresHaritasiSayfa'], 'ogrenci_listele');
    $router->get('/panel/ogrenciler/ozel-notlar', [OgrenciController::class, 'ozelNotlarSayfa'], 'ogrenci_listele');
    $router->get('/panel/bekleyen-veliler', [BekleyenVeliController::class, 'sayfa'], 'bekleyen_veli_listele');
    $router->get('/panel/veliler', [VeliController::class, 'sayfa'], 'veli_listele');
    $router->get('/panel/veli-onamlari', [VeliOnamController::class, 'panel'], 'veli_listele');
    $router->get('/panel/veli-onamlari/qr.svg', [VeliOnamController::class, 'qr'], 'veli_listele');
    $router->get('/panel/veli-onamlari/pdf', [VeliOnamController::class, 'pdf'], 'veli_listele');
    $router->get('/panel/onam-formlari/pdf', [OnamFormuController::class, 'pdf'], 'ogrenci_listele');
    $router->get('/panel/gruplar', [GrupController::class, 'sayfa'], 'grup_listele');
    $router->get('/panel/gruplar/kontenjanlar', [GrupController::class, 'kontenjanlarSayfa'], 'grup_listele');
    $router->get('/panel/paketler', [PaketController::class, 'listeSayfa'], 'paket_listele');
    $router->get('/panel/paketler/tanimla', [PaketController::class, 'sayfa'], 'paket_ekle');
    $router->get('/panel/odemeler', [OdemeController::class, 'sayfa'], 'odeme_listele');
    $router->get('/panel/odemeler/borclular', [OdemeController::class, 'borclularSayfa'], 'odeme_listele');
    $router->get('/panel/odemeler/tahsilat-takibi', [OdemeController::class, 'tahsilatTakibiSayfa'], 'odeme_listele');
    $router->get('/panel/odemeler/tahsilatlar', [OdemeController::class, 'tahsilatlarSayfa'], 'odeme_listele');
    $router->get('/panel/odemeler/tahsilatlar.xlsx', [OdemeController::class, 'tahsilatlarExcel'], 'odeme_listele');
    $router->get('/panel/odemeler/giderler', [OdemeController::class, 'giderlerSayfa'], 'odeme_listele');
    $router->get('/panel/odemeler/kasalar', [KasaController::class, 'sayfa'], 'odeme_listele');
    $router->get('/panel/cariler', [CariController::class, 'sayfa'], 'odeme_listele');
    $router->get('/panel/faturalar', [FaturaController::class, 'sayfa'], 'odeme_listele');
    $router->get('/panel/faturalar/detay', [FaturaController::class, 'detay'], 'odeme_listele');
    $router->get('/panel/faturalar/taslak-onizleme', [FaturaController::class, 'taslakOnizleme'], 'odeme_listele');
    $router->get('/panel/faturalar/dosya', [FaturaController::class, 'dosya'], 'odeme_listele');
    $router->post('/panel/faturalar/toplu-indir', [FaturaController::class, 'topluIndir'], 'odeme_listele');
    $router->get('/panel/faturalar/entegrasyon-ayarlari', [FaturaController::class, 'ayarlar'], 'fatura_entegrasyon_yonet');
    $router->get('/panel/randevular', [RandevuController::class, 'sayfa'], 'randevu_listele');
    $router->get('/panel/randevular/yeni', [RandevuController::class, 'yeni'], 'randevu_ekle');
    $router->get('/panel/gunluk-kayitlar', [GunlukKayitController::class, 'sayfa'], 'yoklama_listele');
    $router->post('/panel/gunluk-kayitlar/rapor.pdf', [GunlukKayitController::class, 'raporPdf'], 'randevu_ekle');
    $router->get('/panel/haftalik-temalar', [HaftalikTemaController::class, 'temalarSayfa'], 'tema_yonet');
    $router->get('/panel/raporlar', [RaporController::class, 'sayfa'], 'rapor_ozet');
    $router->get('/panel/finans/gelir-gider', [RaporController::class, 'gelirGiderSayfa'], 'rapor_ozet');
    $router->get('/panel/sms', [SmsController::class, 'sayfa'], 'sms_goruntule');
    $router->get('/panel/sms/raporlar', [SmsController::class, 'raporlarSayfa'], 'sms_rapor_goruntule');
    $router->get('/panel/kullanicilar', [KullaniciController::class, 'sayfa'], 'kullanici_yonet');
    $router->get('/panel/personeller', [PersonelController::class, 'sayfa'], 'personel_listele');
    $router->get('/panel/personeller/puantaj.xlsx', [PersonelController::class, 'excel'], 'personel_listele');
    $router->get('/panel/sistem/kurumlar', [KurumController::class, 'sayfa'], 'sistem_yonetimi');
    $router->post('/panel/sistem/kurumlar/logo', [KurumController::class, 'logoYukle'], 'sistem_yonetimi');
};
